import sqlite3
conn = sqlite3.connect("econ.db")
cur = conn.cursor()
cur.execute("DROP TABLE IF EXISTS prices")
cur.execute("DROP TABLE IF EXISTS indicators")
cur.execute("CREATE TABLE prices (id INTEGER PRIMARY KEY AUTOINCREMENT, ticker TEXT, date TEXT, open REAL, close REAL, UNIQUE(ticker, date))")
cur.execute("CREATE TABLE indicators (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, date TEXT, value REAL, UNIQUE(name, date))")
conn.commit()
conn.close()
print("done")
